name: Ubuntu CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@bionic
        with:
          codecov-enabled: true
          cmake-args: "-DCMAKE_INSTALL_PREFIX=/usr"
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@focal
        with:
          cmake-args: "-DCMAKE_INSTALL_PREFIX=/usr"
